import {
  Aggrement,
  Back,
  Bell,
  Car,
  Home,
  Info,
  Inkort,
  Logout,
  Sheild,
} from '../../assets/Images/SVGs/Continue';

export const Rides = [
  {
    Car: require('../../assets/Images/PNG/Car.png'),
    Name: 'Ekonomi',
    Price: '5',
    limit: '3',
    type: 'Taxi',
  },
  {
    Car: require('../../assets/Images/PNG/Car2.png'),
    Name: 'Storbil-upp till 7 passagerare',
    Price: '8',
    limit: '4',
    type: 'HatchBack',
  },
];

export const Draw = [
  {
    img: Home,
    title: 'Boka en taxi',
  },
  {
    img: Car,
    title: 'Mina bokningar',
  },
  {
    img: Sheild,
    title: 'Betalningsalternativ',
  },
  {
    img: Bell,
    title: 'Push meddelande',
  },

  {
    img: Info,
    title: 'Om oss',
  },
  {
    img: Aggrement,
    title: 'Villkor och Integritets Policy',
  },
];
export const Ddraw = [
  {
    img: Car,
    title: 'Mina körningar',
  },
  {
    img: Inkort,
    title: 'Inkört',
  },
  {
    img: Bell,
    title: 'Meddelanden',
  },
  {
    img: Info,
    title: 'Om oss',
  },
  {
    img: Aggrement,
    title: 'Villkor och Integritets Policy',
  },
  {
    img: Logout,
    title: 'Logga ut',
  },
];

export const Planei = [
  {
    From: 'Från',
    To: 'Till',
    Standard: 'Standard',
    Bigcar: 'Storbil',
  },

  {
    From: 'Stockholm C',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 760,
  },
  {
    From: 'Stockholm C',
    To: 'Skavsta Flygplats',
    Standard: 1190,
    Bigcar: 1550,
  },
  {
    From: 'Alvik/ Smedslätten',
    To: 'Arlanda Flygplats',
    Standard: 510,
    Bigcar: 745,
  },
  {
    From: 'Arlanda Flygplats',
    To: 'Arlanda Flygplatsområde',
    Standard: 205,
    Bigcar: 275,
  },
  {
    From: 'Aspudden',
    To: 'Arlanda Flygplats',
    Standard: 570,
    Bigcar: 804,
  },
  {
    From: 'Botkyrka, Hallunda/ Alby',
    To: 'Arlanda Flygplats',
    Standard: 745,
    Bigcar: 985,
  },
  {
    From: 'Botkyrka, Tumba',
    To: 'Arlanda Flygplats',
    Standard: 830,
    Bigcar: 1070,
  },
  {
    From: 'Bredäng/ Sätra',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Bromma Flyg',
    To: 'Arlanda Flygplats',
    Standard: 520,
    Bigcar: 760,
  },
  {
    From: 'Brommaplan',
    To: 'Arlanda Flygplats',
    Standard: 480,
    Bigcar: 720,
  },
  {
    From: 'Bromsten, Spånga',
    To: 'Arlanda Flygplats',
    Standard: 520,
    Bigcar: 760,
  },
  {
    From: 'Bålsta',
    To: 'Arlanda Flygplats',
    Standard: 745,
    Bigcar: 985,
  },
  {
    From: 'Danderyd, Djursholm',
    To: 'Arlanda Flygplats',
    Standard: 520,
    Bigcar: 760,
  },
  {
    From: 'Danderyd, Enebyberg',
    To: 'Arlanda Flygplats',
    Standard: 520,
    Bigcar: 760,
  },
  {
    From: 'Danderyd, Klingsta, Nora',
    To: 'Arlanda Flygplats',
    Standard: 520,
    Bigcar: 760,
  },
  {
    From: 'Danderyd, Mörby',
    To: 'Arlanda Flygplats',
    Standard: 520,
    Bigcar: 760,
  },
  {
    From: 'Danderyd, Stocksund/ Ösby',
    To: 'Arlanda Flygplats',
    Standard: 520,
    Bigcar: 760,
  },
  {
    From: 'Ekerö, Adelsö',
    To: 'Arlanda Flygplats',
    Standard: 1190,
    Bigcar: 1428,
  },
  {
    From: 'Ekerö, Drottningholm/ Lovön',
    To: 'Arlanda Flygplats',
    Standard: 590,
    Bigcar: 830,
  },
  {
    From: 'Ekerö, Ekerö C/ Träkvista',
    To: 'Arlanda Flygplats',
    Standard: 710,
    Bigcar: 950,
  },
  {
    From: 'Ekerö, Färentuna',
    To: 'Arlanda Flygplats',
    Standard: 830,
    Bigcar: 1070,
  },
  {
    From: 'Ekerö, Munsö',
    To: 'Arlanda Flygplats',
    Standard: 950,
    Bigcar: 1190,
  },
  {
    From: 'Ekerö, Nyckelby',
    To: 'Arlanda Flygplats',
    Standard: 740,
    Bigcar: 1010,
  },
  {
    From: 'Ekerö, Stenhamra',
    To: 'Arlanda Flygplats',
    Standard: 745,
    Bigcar: 985,
  },
  {
    From: 'Enköping',
    To: 'Arlanda Flygplats',
    Standard: 1190,
    Bigcar: 1420,
  },
  {
    From: 'Enskede/ Globen',
    To: 'Arlanda Flygplats',
    Standard: 565,
    Bigcar: 805,
  },
  {
    From: 'Fagersjö',
    To: 'Arlanda Flygplats',
    Standard: 660,
    Bigcar: 900,
  },
  {
    From: 'Farsta',
    To: 'Arlanda Flygplats',
    Standard: 660,
    Bigcar: 900,
  },
  {
    From: 'Fittja',
    To: 'Arlanda Flygplats',
    Standard: 708,
    Bigcar: 950,
  },
  {
    From: 'Flysta, Spånga',
    To: 'Arlanda Flygplats',
    Standard: 470,
    Bigcar: 710,
  },
  {
    From: 'Frescati',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 760,
  },
  {
    From: 'Fruängen',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Gamla Enskede',
    To: 'Arlanda Flygplats',
    Standard: 590,
    Bigcar: 830,
  },
  {
    From: 'Gröndal',
    To: 'Arlanda Flygplats',
    Standard: 565,
    Bigcar: 805,
  },
  {
    From: 'Gullmarsplan',
    To: 'Arlanda Flygplats',
    Standard: 565,
    Bigcar: 805,
  },
  {
    From: 'Hammarby Sjöstad',
    To: 'Arlanda Flygplats',
    Standard: 565,
    Bigcar: 805,
  },
  {
    From: 'Haninge, Handen',
    To: 'Arlanda Flygplats',
    Standard: 805,
    Bigcar: 1044,
  },
  {
    From: 'Haninge, Jordbro',
    To: 'Arlanda Flygplats',
    Standard: 840,
    Bigcar: 1080,
  },
  {
    From: 'Haninge, Muskö',
    To: 'Arlanda Flygplats',
    Standard: 1465,
    Bigcar: 1705,
  },
  {
    From: 'Haninge, Vendelsö',
    To: 'Arlanda Flygplats',
    Standard: 805,
    Bigcar: 1045,
  },
  {
    From: 'Haninge, Västerhaninge',
    To: 'Arlanda Flygplats',
    Standard: 950,
    Bigcar: 1190,
  },
  {
    From: 'Haninge, Årsta Havsbad',
    To: 'Arlanda Flygplats',
    Standard: 1070,
    Bigcar: 1310,
  },
  {
    From: 'Huddinge, Flemingsberg',
    To: 'Arlanda Flygplats',
    Standard: 745,
    Bigcar: 985,
  },
  {
    From: 'Huddinge, Fullersta',
    To: 'Arlanda Flygplats',
    Standard: 660,
    Bigcar: 900,
  },
  {
    From: 'Huddinge, Gladökvarn',
    To: 'Arlanda Flygplats',
    Standard: 745,
    Bigcar: 985,
  },
  {
    From: 'Huddinge, Glömsta',
    To: 'Arlanda Flygplats',
    Standard: 710,
    Bigcar: 950,
  },
  {
    From: 'Huddinge, Huddinge C',
    To: 'Arlanda Flygplats',
    Standard: 710,
    Bigcar: 950,
  },
  {
    From: 'Huddinge, Kungens Kurva',
    To: 'Arlanda Flygplats',
    Standard: 660,
    Bigcar: 900,
  },
  {
    From: 'Huddinge, Lissma',
    To: 'Arlanda Flygplats',
    Standard: 805,
    Bigcar: 1045,
  },
  {
    From: 'Huddinge, Masmo',
    To: 'Arlanda Flygplats',
    Standard: 710,
    Bigcar: 950,
  },
  {
    From: 'Huddinge, Segeltorp',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Huddinge, Skogås',
    To: 'Arlanda Flygplats',
    Standard: 710,
    Bigcar: 950,
  },
  {
    From: 'Huddinge, Snättringe',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Huddinge, Stuvsta',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Huddinge, Trångsund',
    To: 'Arlanda Flygplats',
    Standard: 710,
    Bigcar: 950,
  },
  {
    From: 'Huddinge, Vidja',
    To: 'Arlanda Flygplats',
    Standard: 710,
    Bigcar: 950,
  },
  {
    From: 'Husby/ Akalla',
    To: 'Arlanda Flygplats',
    Standard: 420,
    Bigcar: 650,
  },
  {
    From: 'Hägerstensåsen',
    To: 'Arlanda Flygplats',
    Standard: 590,
    Bigcar: 830,
  },
  {
    From: 'Hässelby Gård',
    To: 'Arlanda Flygplats',
    Standard: 840,
    Bigcar: 720,
  },
  {
    From: 'Hässelby Villastad',
    To: 'Arlanda Flygplats',
    Standard: 495,
    Bigcar: 725,
  },
  {
    From: 'Högdalen/ Bandhagen',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Hökarängen',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Johannefred',
    To: 'Arlanda Flygplats',
    Standard: 470,
    Bigcar: 705,
  },
  {
    From: 'Järfälla, Barkarby/ Skälby',
    To: 'Arlanda Flygplats',
    Standard: 520,
    Bigcar: 760,
  },
  {
    From: 'Järfälla, Jakobsberg',
    To: 'Arlanda Flygplats',
    Standard: 460,
    Bigcar: 695,
  },
  {
    From: 'Järfälla, Kallhäll/ Stäket',
    To: 'Arlanda Flygplats',
    Standard: 450,
    Bigcar: 690,
  },
  {
    From: 'Järfälla, Viksjö',
    To: 'Arlanda Flygplats',
    Standard: 470,
    Bigcar: 710,
  },
  {
    From: 'Kista',
    To: 'Arlanda Flygplats',
    Standard: 430,
    Bigcar: 660,
  },
  {
    From: 'Knivsta Alsike',
    To: 'Arlanda Flygplats',
    Standard: 520,
    Bigcar: 670,
  },
  {
    From: 'Knivsta, Centrum',
    To: 'Arlanda Flygplats',
    Standard: 420,
    Bigcar: 660,
  },
  {
    From: 'Kärrtorp/ Bagarmossen',
    To: 'Arlanda Flygplats',
    Standard: 590,
    Bigcar: 830,
  },
  {
    From: 'Lidingö, Brevik',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Lidingö, Elfvik',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Lidingö, Sticklinge/ Näset',
    To: 'Arlanda Flygplats',
    Standard: 590,
    Bigcar: 830,
  },
  {
    From: 'Lidingö, Vasaplatsen',
    To: 'Arlanda Flygplats',
    Standard: 590,
    Bigcar: 830,
  },
  {
    From: 'Liljeholmen',
    To: 'Arlanda Flygplats',
    Standard: 565,
    Bigcar: 805,
  },
  {
    From: 'Lunda/ Solhem, Spånga',
    To: 'Arlanda Flygplats',
    Standard: 520,
    Bigcar: 760,
  },
  {
    From: 'Långbro',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Långsjö, Herrängen',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },

  {
    From: 'Mariehäll/ Solvalla',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Midsommarkransen',
    To: 'Arlanda Flygplats',
    Standard: 565,
    Bigcar: 805,
  },
  {
    From: 'Mälarhöjden/ Axelsberg',
    To: 'Arlanda Flygplats',
    Standard: 590,
    Bigcar: 830,
  },
  {
    From: 'Märsta',
    To: 'Arlanda Flygplats',
    Standard: 276,
    Bigcar: 455,
  },
  {
    From: 'Nacka, Björknäs',
    To: 'Arlanda Flygplats',
    Standard: 745,
    Bigcar: 985,
  },
  {
    From: 'Nacka, Duvnäs/ Skuru',
    To: 'Arlanda Flygplats',
    Standard: 660,
    Bigcar: 900,
  },
  {
    From: 'Nacka, Fisksätra',
    To: 'Arlanda Flygplats',
    Standard: 720,
    Bigcar: 960,
  },
  {
    From: 'Nacka, Henriksdal/ Sickla',
    To: 'Arlanda Flygplats',
    Standard: 565,
    Bigcar: 805,
  },
  {
    From: 'Nacka, Järla/ Storängen',
    To: 'Arlanda Flygplats',
    Standard: 590,
    Bigcar: 830,
  },
  {
    From: 'Nacka, Orminge/ Lännersta',
    To: 'Arlanda Flygplats',
    Standard: 745,
    Bigcar: 980,
  },
  {
    From: 'Nacka, Saltsjöbaden',
    To: 'Arlanda Flygplats',
    Standard: 755,
    Bigcar: 995,
  },
  {
    From: 'Nacka, Tippen/ Igelboda',
    To: 'Arlanda Flygplats',
    Standard: 745,
    Bigcar: 945,
  },
  {
    From: 'Nacka, Älgö',
    To: 'Arlanda Flygplats',
    Standard: 775,
    Bigcar: 995,
  },
  {
    From: 'Nacka, Älta',
    To: 'Arlanda Flygplats',
    Standard: 710,
    Bigcar: 950,
  },
  {
    From: 'Nockeby',
    To: 'Arlanda Flygplats',
    Standard: 505,
    Bigcar: 745,
  },
  {
    From: 'Norrtälje',
    To: 'Arlanda Flygplats',
    Standard: 830,
    Bigcar: 1065,
  },
  {
    From: 'Norrtälje, Rimbo',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Norrtälje, Yxlan/ Blidö',
    To: 'Arlanda Flygplats',
    Standard: 1090,
    Bigcar: 1310,
  },
  {
    From: 'Nynäshamn C/ Stora Vika',
    To: 'Arlanda Flygplats',
    Standard: 1310,
    Bigcar: 1545,
  },
  {
    From: 'Nynäshamn, Torö',
    To: 'Arlanda Flygplats',
    Standard: 1465,
    Bigcar: 1705,
  },
  {
    From: 'Nynäshamn, Ösmo/ Sorunda',
    To: 'Arlanda Flygplats',
    Standard: 1190,
    Bigcar: 1430,
  },
  {
    From: 'Nälsta, Spånga',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Rinkeby',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Rågsved/ Hagsätra',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Salem, Rönninge',
    To: 'Arlanda Flygplats',
    Standard: 865,
    Bigcar: 1105,
  },
  {
    From: 'Sigtuna',
    To: 'Arlanda Flygplats',
    Standard: 360,
    Bigcar: 550,
  },
  {
    From: 'Sigtuna Norra',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 675,
  },
  {
    From: 'Skarpnäck/ Sköndal N',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Skavsta Flygplats',
    To: 'Arlanda Flygplats',
    Standard: 1795,
    Bigcar: 2035,
  },
  {
    From: 'Skärholmen/ Vårberg',
    To: 'Arlanda Flygplats',
    Standard: 660,
    Bigcar: 900,
  },
  {
    From: 'Sköndal S',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Solberga/ Västberga',
    To: 'Arlanda Flygplats',
    Standard: 590,
    Bigcar: 830,
  },
  {
    From: 'Sollentuna C/ Tureberg',
    To: 'Arlanda Flygplats',
    Standard: 420,
    Bigcar: 660,
  },
  {
    From: 'Sollentuna, Edsberg',
    To: 'Arlanda Flygplats',
    Standard: 420,
    Bigcar: 660,
  },
  {
    From: 'Sollentuna, Rotebro',
    To: 'Arlanda Flygplats',
    Standard: 395,
    Bigcar: 635,
  },
  {
    From: 'Sollentuna, Sjöberg',
    To: 'Arlanda Flygplats',
    Standard: 420,
    Bigcar: 660,
  },
  {
    From: 'Solna Business Park',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Solna C',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Solna, Bergshamra',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Solna, Hagalund, Frösunda',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Solna, Huvudsta',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Solna, Järva Krog',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Solna, Karolinska',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Solna, Råsunda',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Sundbyberg, Duvbo/ Rissne',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Sundbyberg, Hallonbergen',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Sundbyberg, Lilla Alby/ Vreten',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Sundbybergs C',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Svedmyra/ Stureby',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Södertälje',
    To: 'Arlanda Flygplats',
    Standard: 1020,
    Bigcar: 1260,
  },
  {
    From: 'Södertälje, Järna',
    To: 'Arlanda Flygplats',
    Standard: 1310,
    Bigcar: 1550,
  },
  {
    From: 'Tallkrogen/ Gubbängen',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Tensta',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Traneberg',
    To: 'Arlanda Flygplats',
    Standard: 480,
    Bigcar: 720,
  },
  {
    From: 'Trosa',
    To: 'Arlanda Flygplats',
    Standard: 1550,
    Bigcar: 1790,
  },
  {
    From: 'Tullinge',
    To: 'Arlanda Flygplats',
    Standard: 745,
    Bigcar: 945,
  },
  {
    From: 'Tyresö, Brevik',
    To: 'Arlanda Flygplats',
    Standard: 805,
    Bigcar: 1045,
  },
  {
    From: 'Täby C',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Täby Kyrkby',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Täby, Arninge',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Täby, Näsby Park/ Lahäll',
    To: 'Arlanda Flygplats',
    Standard: 455,
    Bigcar: 695,
  },
  {
    From: 'Täby, Skarpäng/ Ensta',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Upplands Bro, Bro',
    To: 'Arlanda Flygplats',
    Standard: 745,
    Bigcar: 945,
  },
  {
    From: 'Upplands Bro, Kungsängen',
    To: 'Arlanda Flygplats',
    Standard: 590,
    Bigcar: 830,
  },
  {
    From: 'Upplands Bro, Råby',
    To: 'Arlanda Flygplats',
    Standard: 590,
    Bigcar: 830,
  },
  {
    From: 'Upplands Väsby',
    To: 'Arlanda Flygplats',
    Standard: 320,
    Bigcar: 470,
  },
  {
    From: 'Upplands Väsby, Bollstanäs',
    To: 'Arlanda Flygplats',
    Standard: 400,
    Bigcar: 635,
  },
  {
    From: 'Uppsala',
    To: 'Arlanda Flygplats',
    Standard: 505,
    Bigcar: 745,
  },
  {
    From: 'Vallentuna',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Vallentuna, Brottby',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Vallentuna, Kårsta',
    To: 'Arlanda Flygplats',
    Standard: 625,
    Bigcar: 865,
  },
  {
    From: 'Vallentuna, Lindholmen',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Vaxholm, Rindö',
    To: 'Arlanda Flygplats',
    Standard: 950,
    Bigcar: 990,
  },
  {
    From: 'Vaxholm/ Resarö',
    To: 'Arlanda Flygplats',
    Standard: 755,
    Bigcar: 995,
  },
  {
    From: 'Vinsta/ Kälvesta',
    To: 'Arlanda Flygplats',
    Standard: 525,
    Bigcar: 765,
  },
  {
    From: 'Vällingby',
    To: 'Arlanda Flygplats',
    Standard: 470,
    Bigcar: 710,
  },
  {
    From: 'Värmdö, Gustavsberg',
    To: 'Arlanda Flygplats',
    Standard: 830,
    Bigcar: 1070,
  },
  {
    From: 'Värmdö, Hemmesta',
    To: 'Arlanda Flygplats',
    Standard: 865,
    Bigcar: 1105,
  },
  {
    From: 'Värmdö, Ingarö',
    To: 'Arlanda Flygplats',
    Standard: 865,
    Bigcar: 1105,
  },
  {
    From: 'Värmdö, Skärmarö',
    To: 'Arlanda Flygplats',
    Standard: 1095,
    Bigcar: 1335,
  },
  {
    From: 'Värmdö, Stavsnäs',
    To: 'Arlanda Flygplats',
    Standard: 1440,
    Bigcar: 1500,
  },
  {
    From: 'Värmdö, Tynningö',
    To: 'Arlanda Flygplats',
    Standard: 1440,
    Bigcar: 1500,
  },
  {
    From: 'Värmdö, Vindö',
    To: 'Arlanda Flygplats',
    Standard: 1070,
    Bigcar: 1430,
  },
  {
    From: 'Västertorp',
    To: 'Arlanda Flygplats',
    Standard: 590,
    Bigcar: 830,
  },
  {
    From: 'Västerås',
    To: 'Arlanda Flygplats',
    Standard: 1380,
    Bigcar: 1740,
  },
  {
    From: 'Älvsjö',
    To: 'Arlanda Flygplats',
    Standard: 540,
    Bigcar: 830,
  },
  {
    From: 'Örby Slott',
    To: 'Arlanda Flygplats',
    Standard: 540,
    Bigcar: 830,
  },
  {
    From: 'Östberga',
    To: 'Arlanda Flygplats',
    Standard: 540,
    Bigcar: 830,
  },
  {
    From: 'Årsta Torg/ Årsta V',
    To: 'Arlanda Flygplats',
    Standard: 540,
    Bigcar: 830,
  },
  {
    From: 'Österåker',
    To: 'Arlanda Flygplats',
    Standard: 795,
    Bigcar: 1035,
  },
  {
    From: 'Österåker, Ljusterö',
    To: 'Arlanda Flygplats',
    Standard: 1310,
    Bigcar: 1550,
  },
  {
    From: 'Österåker, Svinninge',
    To: 'Arlanda Flygplats',
    Standard: 710,
    Bigcar: 950,
  },
  {
    From: 'Österåker, Åkersberga',
    To: 'Arlanda Flygplats',
    Standard: 755,
    Bigcar: 995,
  },
];
